# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('tasks_planned', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_missed', models.PositiveIntegerField(default=0)),
                ('personal_completed', models.PositiveIntegerField(default=0)),
                ('business_completed', models.PositiveIntegerField(default=0)),
                ('team_completed', models.PositiveIntegerField(default=0)),
                ('guest_completed', models.PositiveIntegerField(default=0)),
                ('business_minutes', models.PositiveIntegerField(default=0)),
                ('personal_minutes', models.PositiveIntegerField(default=0)),
                ('business_target_minutes', models.PositiveIntegerField(default=0)),
                ('sleep_minutes', models.PositiveIntegerField(default=0)),
                ('sleep_target_minutes', models.PositiveIntegerField(default=0)),
                ('routine_items_total', models.PositiveIntegerField(default=0)),
                ('routine_items_completed', models.PositiveIntegerField(default=0)),
                ('project_minutes', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_daily_summary',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='daily_summary_lookup')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily_summary')],
            },
        ),
    ]
