# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharing', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelinkitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_items', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['owner', '-created_at'], name='share_owner_created'),
        ),
        migrations.AddIndex(
            model_name='shareguestsession',
            index=models.Index(fields=['share', '-last_seen_at'], name='guest_share_seen'),
        ),
        migrations.AddConstraint(
            model_name='sharelinkitem',
            constraint=models.UniqueConstraint(fields=('share', 'task'), name='uniq_share_task'),
        ),
    ]
