# Generated by Django 5.1.15 on 2026-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_kind', models.CharField(choices=[('user', 'User'), ('guest', 'Guest'), ('ai', 'AI'), ('telegram', 'Telegram'), ('system', 'System')], default='user', max_length=10)),
                ('actor_display', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile_web', 'Mobile web'), ('telegram', 'Telegram'), ('team', 'Team'), ('share_link', 'Share link'), ('ai_web', 'AI (web)'), ('ai_telegram', 'AI (Telegram)'), ('system', 'System')], default='web', max_length=20)),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.BigIntegerField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('group', 'Group visible')], default='group', max_length=10)),
                ('in_feed', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'collab_activity_event',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('body', models.TextField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile_web', 'Mobile web'), ('telegram', 'Telegram'), ('team', 'Team'), ('share_link', 'Share link'), ('ai_web', 'AI (web)'), ('ai_telegram', 'AI (Telegram)'), ('system', 'System')], default='web', max_length=20)),
            ],
            options={
                'db_table': 'collab_comment',
                'ordering': ['created_at'],
            },
        ),
    ]
