# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collab', '0001_initial'),
        ('projects', '0001_initial'),
        ('sharing', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='actor_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='sharing.shareguestsession'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='projects.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['project', '-id'], name='activity_project'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['owner_user', '-id'], name='activity_owner'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['target_type', 'target_id'], name='activity_target'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['name', '-id'], name='activity_name'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', 'created_at'], name='comment_task'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['project', 'created_at'], name='comment_project'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task__isnull', False), ('project__isnull', True)), models.Q(('task__isnull', True), ('project__isnull', False)), _connector='OR'), name='comment_single_target'),
        ),
    ]
