# Generated by Django 5.1.15 on 2026-09-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.BigIntegerField()),
                ('source_hash', models.CharField(max_length=64)),
                ('source_lang', models.CharField(blank=True, max_length=8)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'translations_translation',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='translation_status_updated')],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'target_id'), name='uniq_translation_target')],
            },
        ),
    ]
