# Generated by Django 5.1.15 on 2026-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('general', 'Project'), ('startup', 'Startup')], db_index=True, default='general', max_length=12),
        ),
    ]
