# Generated by Django 5.1.15 on 2026-09-28 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCheckin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "subject",
                    models.CharField(
                        choices=[("project", "Project"), ("crypto", "Crypto world")], default="project", max_length=10
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_checkins",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_daily_checkin",
                "ordering": ["date", "created_at"],
                "indexes": [models.Index(fields=["user", "date"], name="projects_da_user_id_5e8ac0_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("project__isnull", False)),
                        fields=("user", "date", "project"),
                        name="daily_checkin_one_per_project_day",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("subject", "crypto")),
                        fields=("user", "date"),
                        name="daily_checkin_one_crypto_per_day",
                    ),
                ],
            },
        ),
    ]
