# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('important', 'Important only'), ('all', 'All'), ('custom', 'Custom')], default='important', max_length=10)),
                ('telegram_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('on_task_created', models.BooleanField(default=False)),
                ('on_task_completed', models.BooleanField(default=True)),
                ('on_task_reopened', models.BooleanField(default=True)),
                ('on_subtask_created', models.BooleanField(default=False)),
                ('on_subtask_completed', models.BooleanField(default=True)),
                ('on_comment_created', models.BooleanField(default=True)),
                ('on_deadline_changed', models.BooleanField(default=True)),
                ('on_assignment_changed', models.BooleanField(default=True)),
                ('on_member_joined', models.BooleanField(default=True)),
                ('on_member_removed', models.BooleanField(default=True)),
                ('on_share_task_completed', models.BooleanField(default=True)),
                ('on_share_opened', models.BooleanField(default=False)),
                ('on_reminder', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('reminder', 'Reminder'), ('deadline', 'Deadline'), ('team', 'Team activity'), ('comment', 'Comment'), ('guest', 'Guest activity'), ('assignment', 'Assignment'), ('ai', 'AI'), ('summary', 'Summary'), ('system', 'System')], default='system', max_length=12)),
                ('event_name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=120)),
                ('activity_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='collab.activityevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', '-id'], name='notification_user'), models.Index(fields=['user', 'read_at'], name='notification_unread')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='uniq_notification_dedupe')],
            },
        ),
    ]
