# Generated by Django 5.1.15 on 2026-09-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kept', models.BooleanField(default=True)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='routines.rule')),
            ],
            options={
                'db_table': 'routines_rule_completion',
                'indexes': [models.Index(fields=['rule', '-date'], name='rule_completion_lookup')],
                'constraints': [models.UniqueConstraint(fields=('rule', 'date'), name='uniq_rule_completion')],
            },
        ),
    ]
