# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile_web', 'Mobile web'), ('telegram', 'Telegram'), ('team', 'Team'), ('share_link', 'Share link'), ('ai_web', 'AI (web)'), ('ai_telegram', 'AI (Telegram)'), ('system', 'System')], default='ai_web', max_length=20)),
                ('input_text', models.TextField()),
                ('model', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('proposed', 'Awaiting confirmation'), ('executed', 'Executed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('reply_text', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_action',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', '-id'], name='ai_action_user'), models.Index(fields=['status', '-id'], name='ai_action_status')],
            },
        ),
    ]
