# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='activity_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='collab.activityevent'),
        ),
    ]
