# Generated by Django 5.1.15 on 2026-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userpreference_routine_on_weekends"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="crypto_world_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="crypto_world_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
