# Generated by Django 5.1.15 on 2026-10-02 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreference_crypto_world_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helping_links', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_assistant_link',
                'constraints': [models.UniqueConstraint(fields=('principal', 'helper'), name='uniq_assistant_link'), models.CheckConstraint(condition=models.Q(('principal', models.F('helper')), _negated=True), name='assistant_link_not_self')],
            },
        ),
    ]
