# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freq', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('byweekday', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None)),
                ('bymonthday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('until', models.DateField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('occurrences_created', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tasks_recurrence_rule',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], db_index=True, default='personal', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=12)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('group', 'Group visible')], default='group', max_length=10)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('due_has_time', models.BooleanField(default=False)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('sort_order', models.IntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_source', models.CharField(blank=True, choices=[('web', 'Web'), ('mobile_web', 'Mobile web'), ('telegram', 'Telegram'), ('team', 'Team'), ('share_link', 'Share link'), ('ai_web', 'AI (web)'), ('ai_telegram', 'AI (Telegram)'), ('system', 'System')], max_length=20)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='sharing.shareguestsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('recurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.recurrencerule')),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_children', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_task',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remind_at', models.DateTimeField()),
                ('message', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_reminder',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'kind', 'status', 'due_at'], name='task_owner_kind_status_due'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='task_project_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='task_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent'], name='task_parent'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', '-completed_at'], name='task_owner_completed'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('completed_at__isnull', True), ('deleted_at__isnull', True)), fields=['owner', 'due_at'], name='task_owner_due_open'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('reminder_at__isnull', False), ('reminder_sent_at__isnull', True)), fields=['reminder_at'], name='task_reminder_pending'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='task_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='task_tags_gin'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('depth__lte', 1)), name='task_max_depth'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), ('depth', 1), _connector='OR'), name='task_subtask_depth_consistent'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['remind_at', 'status'], name='reminder_due'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'status'], name='reminder_user_status'),
        ),
    ]
