# Generated by Django 5.1.15 on 2026-09-01 22:01

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_extensions'),
        ('projects', '0001_initial'),
        ('sharing', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='task_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
