# Generated by Django 5.1.15 on 2026-09-02 18:12

from django.db import migrations, models


def backfill_origin(apps, schema_editor):
    """
    Until now the Business composer could not attach a project, so every existing task that has a
    project was created from inside that project and should stay out of the Business list.
    """
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(project__isnull=False).update(origin="project")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_trigram_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='origin',
            field=models.CharField(choices=[('list', 'Task list'), ('project', 'Project')], db_index=True, default='list', max_length=10),
        ),
        migrations.RunPython(backfill_origin, migrations.RunPython.noop),
    ]
