# Generated by Django 5.1.15 on 2026-09-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_ongoing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='TaskCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_checkins', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_task_checkin',
                'indexes': [models.Index(fields=['task', '-date'], name='task_checkin_lookup')],
                'constraints': [models.UniqueConstraint(fields=('task', 'date'), name='uniq_task_checkin')],
            },
        ),
    ]
