# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_ongoing_checkin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("business", "Business"),
                    ("crypto", "Crypto world"),
                ],
                db_index=True,
                default="personal",
                max_length=10,
            ),
        ),
    ]
