# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collab', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('link_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_connection',
            },
        ),
        migrations.CreateModel(
            name='TelegramUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handled', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'telegram_update_log',
                'indexes': [models.Index(fields=['-created_at'], name='tg_update_created')],
            },
        ),
        migrations.CreateModel(
            name='TelegramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField()),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('text', models.TextField()),
                ('parse_mode', models.CharField(default='HTML', max_length=12)),
                ('reply_markup', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('skipped', 'Skipped')], default='queued', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('activity_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_deliveries', to='collab.activityevent')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_delivery',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', '-id'], name='tg_delivery_user'), models.Index(fields=['status', '-id'], name='tg_delivery_status')],
            },
        ),
    ]
