# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('routines', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_manual', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile_web', 'Mobile web'), ('telegram', 'Telegram'), ('team', 'Team'), ('share_link', 'Share link'), ('ai_web', 'AI (web)'), ('ai_telegram', 'AI (Telegram)'), ('system', 'System')], default='web', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_tracking_sleep',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['owner', '-started_at'], name='sleep_owner_started')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('owner',), name='uniq_running_sleep_per_user')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='business', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('is_manual', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile_web', 'Mobile web'), ('telegram', 'Telegram'), ('team', 'Team'), ('share_link', 'Share link'), ('ai_web', 'AI (web)'), ('ai_telegram', 'AI (Telegram)'), ('system', 'System')], default='web', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.project')),
                ('resumed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumed_entries', to='time_tracking.timeentry')),
                ('routine_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='routines.routineitem')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='tasks.task')),
            ],
            options={
                'db_table': 'time_tracking_entry',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['owner', '-started_at'], name='time_owner_started'), models.Index(fields=['owner', 'category', '-started_at'], name='time_owner_cat_started'), models.Index(fields=['project', '-started_at'], name='time_project_started'), models.Index(fields=['task'], name='time_task')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('owner',), name='uniq_running_timer_per_user'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='time_entry_end_after_start')],
            },
        ),
    ]
