# Generated by Django 5.1.15 on 2026-09-01 21:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompts_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('group', 'Group visible')], default='private', max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('body_length', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_prompts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='projects.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.prompttag')),
            ],
            options={
                'db_table': 'prompts_prompt',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_versions', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompts.prompt')),
            ],
            options={
                'db_table': 'prompts_version',
                'ordering': ['-number'],
            },
        ),
        migrations.AddConstraint(
            model_name='prompttag',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_prompt_tag_owner_slug'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['owner', '-updated_at'], name='prompt_owner_updated'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['owner', 'is_favorite', '-updated_at'], name='prompt_owner_fav'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['project', '-updated_at'], name='prompt_project_updated'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['owner', 'category'], name='prompt_owner_category'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='prompt_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=models.Index(fields=['prompt', '-number'], name='prompt_version_lookup'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('prompt', 'number'), name='uniq_prompt_version_number'),
        ),
    ]
