# Generated by Django 5.1.15 on 2026-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'donations_address',
                'ordering': ['order', 'asset'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'network', 'address'), name='uniq_donation_address')],
            },
        ),
    ]
